[project]
name = "aspcore"
version = "0.0.5"
description = "Classic signal processing toolkit"
readme = "README.md"
authors = [
    {name = "Jesper Brunnström", email = "pvjesper@gmail.com"}
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.14"
dependencies = [
    "jax>=0.9.1",
    "matplotlib>=3.10.8",
    "numba>=0.64.0",
    "numexpr>=2.14.1",
    "numpy>=2.4.3",
    "samplerate>=0.2.3",
    "scipy>=1.17.1",
    "tensorly>=0.9.0",
    "tikzplotlib-patched",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "hypothesis>=6.151.9",
    "pytest>=9.0.2",
]

[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.uv.sources]
tikzplotlib-patched = { git = "https://github.com/JasonGross/tikzplotlib" }

[project.urls]
Documentation = "https://sounds-research.github.io/aspcore/"
Repository = "https://github.com/SOUNDS-RESEARCH/aspcore"
